# Generated by Django 5.2.3 on 2025-08-14 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='max_players',
            new_name='limit',
        ),
        migrations.RemoveField(
            model_name='game',
            name='notes',
        ),
    ]
