# Generated by Django 5.2.3 on 2025-08-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_max_players_game_limit_remove_game_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='Untitled Game', max_length=255),
        ),
    ]
