# Generated by Django 5.2.3 on 2025-07-17 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='skill_level',
            field=models.CharField(default='beginner', max_length=20),
            preserve_default=False,
        ),
    ]
