# Generated by Django 5.2.3 on 2025-08-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time',
        ),
    ]
