# Generated by Django 5.2.3 on 2025-08-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
