# Generated by Django 5.2.3 on 2025-08-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_game_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
