# Generated by Django 5.2.3 on 2025-08-03 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_user'),
        ('api', '0006_player_user'),
    ]

    operations = [
    ]
