# Generated by Django 5.2.3 on 2025-08-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_0003_delete_user_0006_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='preferred_sports',
            field=models.ManyToManyField(blank=True, help_text='List of sports this player prefers to play.', related_name='preferred_by_players', to='api.sport'),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text="Player's gender (optional).", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='skill_level',
            field=models.CharField(blank=True, help_text="Player's self-reported skill level (e.g., Beginner, Intermediate).", max_length=20, null=True),
        ),
    ]
