# Generated by Django 5.2.3 on 2025-08-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_participation_game_alter_participation_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(default=10),
        ),
    ]
